global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'wildtrace'
    static_configs:
      - targets:
        - gateway:8080
        - identity-service:8081
        - registry-service:8082
        - lot-service:8083
        - transfer-service:8084
        - audit-service:8085
        - consumer-api:8086
